name: Deploy from Relay Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]  # ← 중계서버에서 실행

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: masungil/hello-app:latest

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=/home/masungil/actions-runner/_work/.kube/config
          kubectl apply -f k8s/
          kubectl rollout restart deployment hello-app


          